<a href="https://colab.research.google.com/github/viktornester1/course/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

# **00_PyTorch**

---



In [ ]:
import torch

print(torch.__version__)

2.0.1+cu118


---

###**Creating tensors**

---

In [177]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.size()

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [8, 9, 0]],

                       [[5, 5, 5],
                        [5, 5, 5],
                        [5, 5, 6]]])

TENSOR
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [8, 9, 0]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 6]]])


In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 6]])

---

#Random tensors

---
`A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it`



In [ ]:
# random tensor of size (3, 4)
# random_tensor = torch.rand(3, 4)
random_tensor = torch.rand(2, 10, 10)
random_tensor

tensor([[[0.7293, 0.6724, 0.2981, 0.5592, 0.2141, 0.0991, 0.4463, 0.4304,
          0.1555, 0.7958],
         [0.1970, 0.3081, 0.7376, 0.8495, 0.9723, 0.9843, 0.0459, 0.8662,
          0.7370, 0.2289],
         [0.8603, 0.5526, 0.1970, 0.9990, 0.7739, 0.5564, 0.3646, 0.3453,
          0.8989, 0.7453],
         [0.7747, 0.1006, 0.4461, 0.9403, 0.5834, 0.6367, 0.7537, 0.8502,
          0.9595, 0.5554],
         [0.6303, 0.0653, 0.6917, 0.5967, 0.0876, 0.5384, 0.0687, 0.8586,
          0.4172, 0.4016],
         [0.7907, 0.6000, 0.2392, 0.4275, 0.5828, 0.7875, 0.5864, 0.9208,
          0.7859, 0.7845],
         [0.5857, 0.8969, 0.9922, 0.0106, 0.5540, 0.9141, 0.0176, 0.9519,
          0.0281, 0.4391],
         [0.6420, 0.9379, 0.5290, 0.3949, 0.8524, 0.2288, 0.8321, 0.5734,
          0.2991, 0.3066],
         [0.1813, 0.9694, 0.5742, 0.4242, 0.7605, 0.9581, 0.2112, 0.4039,
          0.7851, 0.2491],
         [0.1641, 0.4254, 0.1833, 0.1246, 0.7067, 0.9601, 0.8141, 0.5698,
          0.7365,

In [ ]:
random_tensor.shape, random_tensor.ndim

(torch.Size([2, 10, 10]), 3)

In [ ]:
# Create a random tensor with similiar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B); size=() is an optional synthax
random_image_tensor.shape, "number of dimentions: " ,random_image_tensor.ndim


(torch.Size([3, 224, 224]), 'number of dimentions: ', 3)

---

#**Zeros** and ones

---

In [ ]:
# Create a tensor of zeros
zeros = torch.zeros(4, 4)
x = torch.rand(4,4)
zeros, x

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0.4991, 0.3361, 0.5406, 0.4902],
         [0.3824, 0.9143, 0.3540, 0.7548],
         [0.4977, 0.3802, 0.8139, 0.7919],
         [0.3253, 0.6329, 0.3946, 0.2154]]))

In [ ]:
zeros*x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of ones
ones = torch.ones(4, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

---

#**Create a range of tensors and tensors-like**

---



# Use 'torch.arange()' instead of old 'torch.range()'
torch.range(0, 10)  # bad
torch.arange(0, 10)

In [ ]:
# one_to_ten = torch.arange(start=0, end=1000, step=33)
# one_to_ten = torch.arange(0, 1000, 10)
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
# ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#**Tensor datatypes**

**Note:** Tensor datatypes is one of 3 big errors you'll run into with Pytorch DL:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensor not on right device



In [ ]:
datatype_tensor = torch.tensor([3., 6., 9.],
                               dtype=None, # what datatype is in tensor # точність залежить від кількості біт: більше біт = точніше але повільніше, менше = навпаки. 32 - стандарт, одиниця точності
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not track gradients with this tensors operations
datatype_tensor

tensor([3., 6., 9.])

In [ ]:
datatype_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = datatype_tensor.type(torch.float16) # torch.half is fine too
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
x = float_16_tensor*datatype_tensor
x.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)


# **Getting information from tensors**


In [ ]:
s_tensor = torch.rand(3, 4)
s_tensor

tensor([[0.4351, 0.9698, 0.8766, 0.5357],
        [0.2411, 0.9338, 0.1303, 0.8154],
        [0.1682, 0.1009, 0.1304, 0.7164]])

In [ ]:
print(s_tensor)
print(f"Datatype: {s_tensor.dtype}")
print(f"Shape: {s_tensor.dtype}")
print(f"Device tensor is on: {s_tensor.device}")

tensor([[0.4351, 0.9698, 0.8766, 0.5357],
        [0.2411, 0.9338, 0.1303, 0.8154],
        [0.1682, 0.1009, 0.1304, 0.7164]])
Datatype: torch.float32
Shape: torch.float32
Device tensor is on: cpu


## **Manipulating tensors (tensor operations)**
Tensor operations include:


*   Addition
*   Substractiom
*   Multiplication(element-wise)
*   Division
*   Matrix multiplication



In [ ]:
tens = torch.tensor([1, 2, 3])
tens+10, tens*10, tens-10

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [ ]:
# Matrix multiplications
# Two main ways of mult:
# 1)element-wise 2)matrix multiplication

In [ ]:
# Element wise
tens*tens

tensor([1, 4, 9])

In [ ]:
#Matrix multiplication
torch.matmul(tens, tens)

tensor(14)

### One of the common errors is a shape error

there are 2 rules in matrix multiplications:


1.   inner dimentions must match
*   `(3,2) @ (3,2) won't work`
*   `(2,3) @ (3,2) will work` - inner dimensions are 3, 3
*   `(3 2) @ (2,3) will work` - inner dimensions are 2, 2

2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`



In [ ]:
tens @ tens # is the same as .matmul amd the same as .mm

tensor(14)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [ ]:
# Can use transpose to fix shape mistakes

tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc (aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.





In [ ]:
x = torch.arange(1, 101, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float16))

(tensor(1), tensor(91), tensor(46., dtype=torch.float16))

### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# findsng index of min or max value in tensor
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors.


In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add extra dimention
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view, view shares memory with x
z = x.view(1, 9)
z, z.shape, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(3, 3)
z, z.shape, x


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


You can also rearrange the order of values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [ ]:
x = torch.randn(2, 3, 5)
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channel

# Permute original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[:,:,:]

tensor([[[0.6339, 0.5267, 0.5606],
         [0.6827, 0.3277, 0.3905],
         [0.4641, 0.5173, 0.0919],
         ...,
         [0.6064, 0.6262, 0.9009],
         [0.6127, 0.4671, 0.2997],
         [0.4400, 0.5204, 0.5069]],

        [[0.5895, 0.1052, 0.9953],
         [0.8085, 0.3545, 0.5637],
         [0.9663, 0.7189, 0.7531],
         ...,
         [0.9004, 0.1623, 0.9257],
         [0.3154, 0.6617, 0.5909],
         [0.6081, 0.1028, 0.3637]],

        [[0.3819, 0.2123, 0.3473],
         [0.2129, 0.4798, 0.7348],
         [0.8358, 0.4971, 0.2050],
         ...,
         [0.5641, 0.3184, 0.4581],
         [0.6640, 0.5471, 0.2268],
         [0.4445, 0.6734, 0.9068]],

        ...,

        [[0.0534, 0.8430, 0.5550],
         [0.4000, 0.9554, 0.4332],
         [0.4674, 0.7439, 0.8959],
         ...,
         [0.4797, 0.3697, 0.2710],
         [0.6301, 0.1923, 0.6235],
         [0.2648, 0.0409, 0.2479]],

        [[0.1475, 0.4034, 0.6979],
         [0.6604, 0.0693, 0.5984],
         [0.

## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0] # can do it like that x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket(last dim)
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0,0,1] # "0" is oth dimension, second "0" is first dimension, 1 is a second dimension

tensor(2)

You can also use ":" to select all of target dimension

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

*0 is removing brackets and gives elements within, ":"  outputs all elements in that dim*

In [ ]:
x[:, 2, 2]

tensor([9])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

---

## PyTorch tensors & NumPy

---
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

> **Note:** By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
>
> However, many PyTorch calculations default to using `float32`.
>
> So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use `tensor = torch.from_numpy(array).type(torch.float32)`.

Because we reassigned `tensor` above, if you change the tensor, the array stays the same.

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4944, 0.8863, 0.0841, 0.8174],
        [0.4589, 0.7530, 0.4716, 0.1362],
        [0.9638, 0.3067, 0.8691, 0.0020]])

Tensor B:
tensor([[0.4244, 0.9517, 0.4942, 0.1069],
        [0.9151, 0.3246, 0.2309, 0.4460],
        [0.6235, 0.7070, 0.8879, 0.1602]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

In [ ]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_b = torch.rand(3, 4)

print(f"Tensor a:\n{random_a}\n")
print(f"Tensor b:\n{random_b}\n")
print(f"Does Tensor a equal Tensor b? (anywhere)")
random_a == random_b

Tensor a:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor b:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor a equal Tensor b? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found




###  Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do *much* faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

---

### 3. Putting tensors (and models) on the GPU

---
You can put tensors (and models, we'll see this later) on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

> **Note:** Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
>
> `some_tensor = some_tensor.to(device)`

Let's try creating a tensor and putting it on the GPU (if it's available).

In [ ]:
# default is on cpu
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) method on our `tensor_on_gpu`.

In [ ]:
# No NumPy on gpu
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# To fix gpu tensor woth numpy issue can set it on cpu
tensor_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_on_gpu

array([1, 2, 3])

**Checking how many dimentions - `.ndim`**

**Tensor size - `.shape` or `size()`**

**Synthax for creating 'random_image_tensor' = `torch.rand(size=(3, 224, 224))`
          num of color channels can be in front or in the back**

**Tensor data type - `.dtype` if not specified always float**

**Creating tensors with the size of another tensor - `tensor.[ones/zeros/rand]_like(input)`**

**Getting device from tensor - `.device`**